### ISSUE TITLE
meta: todos

### ISSUE THREAD

**Issue by AlbertoCentonze** [curvefi/scrvusd#7]
- [x] finalize rewards handler
- [x] finish docs
- [x] fee splitter audit
- [x] fee splitter deploy
- [x] fee splitter hook
- [x] fee splitter vote
- [x] publish fee splitter audit
- [x] #14
- [x] #16
- [x] ~finish reviewing 3.0.2~
- [x] ~migrate to 3.0.2~
- [x] ~benchmark 3.0.2 gas~
- [x] events
- [x] uniform docs between `FeeSplitter` and `TWA`
- [x] unit testing (with full code coverage)
- [x] https://github.com/curvefi/stcrvusd/blob/main/contracts/RewardsHandler.vy#L255
- [x] fee splitter integration tests
- [x] deposit limit module
- [x] #31
- [x] #32
- [x] stateful testing (twa) (needs review)
- [x] ~stableswap rate provider for cross chain~ (not necessary for now)
- [x] integration tests with stableswap
- [x] circulating supply as external contract
- [x] rewards midweek
- [x] #33
- [x] deployment scripts
- [x] vote scripts
- [x] audit
